// <auto-generated />
namespace ManagementHighStudySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifyUserSSnUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyUserSSnUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "202106201638249_modifyUserSSnUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
